config/routes.rb
Rails.application.routes.draw do
  get 'user_token/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'  
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :user_token do 
    collection do
      post :set_token
      get  :send_notification
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#toggle" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="toggle"> 
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
            Account <b class="caret"></b>
          </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        </ul>
          <% else %>                 
            <li><%= link_to "Log in", login_path %></li>
          <% end %>  
      </ul>
    </div> 
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <link rel="manifest" href="/manifest.json">    
        <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
  <% if @current_user.present? %>
    <script>
      $(document).ready(function () {
        DisplaySessionTimeout();
      })
    </script>  
  <% end %>
  
    <h3>Expira em <span id='contador'></span></h3>
   
    <%= render 'layouts/header' %>  
      
    <div class="container"> 
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
 
      <div class="modal fade expiration-warning" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="expiration-modal">Sessão quase expirando</h4>
            </div>
            <div class="modal-body">
              <span id="warning" class="hidden">
                Sua sessão está quase expirando. Aperte OK para não perder sua sessão. 
                <h3>Expira em <span id='contador2'></span></h3>
              </span>
              <span id="expire" class="hidden" >
                Sua sessão expirou. Faça login novamente.
              </span>
            </div>
            <div class="modal-footer">
              <%= link_to 'Ok', root_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <%= yield :page_script %>   
  </body>
</html>